// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTask(arg1:models.Task):Promise<models.Task>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetTask(arg1:number):Promise<models.Task>;

export function GetTasks():Promise<Array<models.Task>>;

export function ToggleTask(arg1:number):Promise<void>;

export function UpdateTask(arg1:models.Task):Promise<models.Task>;
