// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['handlers']['TaskHandler']['AddTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['handlers']['TaskHandler']['DeleteTask'](arg1);
}

export function GetTask(arg1) {
  return window['go']['handlers']['TaskHandler']['GetTask'](arg1);
}

export function GetTasks() {
  return window['go']['handlers']['TaskHandler']['GetTasks']();
}

export function ToggleTask(arg1) {
  return window['go']['handlers']['TaskHandler']['ToggleTask'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['handlers']['TaskHandler']['UpdateTask'](arg1);
}
