// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['handlers']['TaskHandler']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['handlers']['TaskHandler']['DeleteTask'](arg1);
}

export function List(arg1) {
  return window['go']['handlers']['TaskHandler']['List'](arg1);
}

export function SetDone(arg1, arg2) {
  return window['go']['handlers']['TaskHandler']['SetDone'](arg1, arg2);
}
