// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {models} from '../models';

export function CreateTask(arg1:handlers.TaskInput):Promise<models.Task>;

export function DeleteTask(arg1:number):Promise<void>;

export function List():Promise<Array<models.Task>>;

export function SetDone(arg1:number,arg2:boolean):Promise<void>;
